### ISSUE TITLE
I did not find any trigger based on location, can you help

### ISSUE THREAD

**Issue by arun-chief** [fschrofner/swip#1]
![qemu-system-x86_64_2018-10-06_16-27-21](https://user-images.githubusercontent.com/16814342/46570638-c737f780-c984-11e8-8695-114363a8981e.png)

**Comment by fschrofner** [comment]
This is probably because you're running the app on an emulator, which does not have Play Services installed. Unfortunately the current implementation of Geofences requires Play Services to be installed and location triggers will not be displayed, when they're not available.

Here's where the option would normally be displayed:
![screenshot_swip_20181009-103803](https://user-images.githubusercontent.com/6865856/46657035-aa333c80-cbaf-11e8-99ea-261750ffd273.png)

**Comment by arun-chief** [comment]
Thanks, it's working.  When I tried after some time
